Repository ROBOTIS-GIT/turtlebot3, pull requests merged in 2025-04, with the labels that each got.

#1084 Relative Move Humble Update
  turtlebot3/CHANGELOG.rst
  turtlebot3/package.xml
  turtlebot3_bringup/CHANGELOG.rst
  turtlebot3_bringup/package.xml
  turtlebot3_cartographer/CHANGELOG.rst
  turtlebot3_cartographer/package.xml
  turtlebot3_description/CHANGELOG.rst
  turtlebot3_description/package.xml
  turtlebot3_example/CHANGELOG.rst
  turtlebot3_example/package.xml
  turtlebot3_example/setup.py
  turtlebot3_example/turtlebot3_example/turtlebot3_absolute_move/__init__.py
  turtlebot3_example/turtlebot3_example/turtlebot3_absolute_move/turtlebot3_absolute_move.py
  turtlebot3_example/turtlebot3_example/turtlebot3_relative_move/__init__.py
  turtlebot3_example/turtlebot3_example/turtlebot3_relative_move/turtlebot3_relative_move.py
  turtlebot3_navigation2/CHANGELOG.rst
  turtlebot3_navigation2/package.xml
  turtlebot3_node/CHANGELOG.rst
  turtlebot3_node/package.xml
  turtlebot3_teleop/CHANGELOG.rst
  turtlebot3_teleop/package.xml
  turtlebot3_teleop/setup.py
Labels: enhancement

#1089 Feature multi robot upgrade
  README.md
  turtlebot3/CHANGELOG.rst
  turtlebot3/package.xml
  turtlebot3_bringup/CHANGELOG.rst
  turtlebot3_bringup/launch/robot.launch.py
  turtlebot3_bringup/launch/turtlebot3_state_publisher.launch.py
  turtlebot3_bringup/package.xml
  turtlebot3_cartographer/CHANGELOG.rst
  turtlebot3_cartographer/package.xml
  turtlebot3_description/CHANGELOG.rst
  turtlebot3_description/package.xml
  turtlebot3_description/urdf/turtlebot3_burger.urdf
  turtlebot3_description/urdf/turtlebot3_waffle.urdf
  turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf
  turtlebot3_example/CHANGELOG.rst
  turtlebot3_example/package.xml
  turtlebot3_example/setup.py
  turtlebot3_navigation2/CHANGELOG.rst
  turtlebot3_navigation2/package.xml
  turtlebot3_node/CHANGELOG.rst
  turtlebot3_node/include/turtlebot3_node/odometry.hpp
  turtlebot3_node/include/turtlebot3_node/sensors/imu.hpp
  turtlebot3_node/include/turtlebot3_node/sensors/joint_state.hpp
  turtlebot3_node/package.xml
  turtlebot3_node/src/odometry.cpp
  turtlebot3_node/src/sensors/imu.cpp
  turtlebot3_node/src/sensors/joint_state.cpp
  turtlebot3_node/src/turtlebot3.cpp
  turtlebot3_teleop/CHANGELOG.rst
  turtlebot3_teleop/package.xml
  turtlebot3_teleop/setup.py
Labels: documentation

#1090 Bump 2.2.8
  README.md
  turtlebot3/CHANGELOG.rst
  turtlebot3/package.xml
  turtlebot3_bringup/CHANGELOG.rst
  turtlebot3_bringup/launch/robot.launch.py
  turtlebot3_bringup/launch/turtlebot3_state_publisher.launch.py
  turtlebot3_bringup/package.xml
  turtlebot3_cartographer/CHANGELOG.rst
  turtlebot3_cartographer/package.xml
  turtlebot3_description/CHANGELOG.rst
  turtlebot3_description/package.xml
  turtlebot3_description/urdf/turtlebot3_burger.urdf
  turtlebot3_description/urdf/turtlebot3_waffle.urdf
  turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf
  turtlebot3_example/CHANGELOG.rst
  turtlebot3_example/package.xml
  turtlebot3_example/setup.py
  turtlebot3_example/turtlebot3_example/turtlebot3_absolute_move/__init__.py
  turtlebot3_example/turtlebot3_example/turtlebot3_absolute_move/turtlebot3_absolute_move.py
  turtlebot3_example/turtlebot3_example/turtlebot3_relative_move/__init__.py
  turtlebot3_example/turtlebot3_example/turtlebot3_relative_move/turtlebot3_relative_move.py
  turtlebot3_navigation2/CHANGELOG.rst
  turtlebot3_navigation2/package.xml
  turtlebot3_node/CHANGELOG.rst
  turtlebot3_node/include/turtlebot3_node/odometry.hpp
  turtlebot3_node/include/turtlebot3_node/sensors/imu.hpp
  turtlebot3_node/include/turtlebot3_node/sensors/joint_state.hpp
  turtlebot3_node/package.xml
  turtlebot3_node/src/odometry.cpp
  turtlebot3_node/src/sensors/imu.cpp
  turtlebot3_node/src/sensors/joint_state.cpp
  turtlebot3_node/src/turtlebot3.cpp
  turtlebot3_teleop/CHANGELOG.rst
  turtlebot3_teleop/package.xml
  turtlebot3_teleop/setup.py
Labels: bump

#1092 fixed typo error
  .github/workflows/ros-ci.yml
  README.md
  turtlebot3/CHANGELOG.rst
  turtlebot3/CMakeLists.txt
  turtlebot3/package.xml
  turtlebot3_bringup/CHANGELOG.rst
  turtlebot3_bringup/package.xml
  turtlebot3_cartographer/CHANGELOG.rst
  turtlebot3_cartographer/package.xml
  turtlebot3_description/CHANGELOG.rst
  turtlebot3_description/package.xml
  turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf
  turtlebot3_example/CHANGELOG.rst
  turtlebot3_example/package.xml
  turtlebot3_example/setup.py
  turtlebot3_navigation2/CHANGELOG.rst
  turtlebot3_navigation2/package.xml
  turtlebot3_node/CHANGELOG.rst
  turtlebot3_node/package.xml
  turtlebot3_teleop/CHANGELOG.rst
  turtlebot3_teleop/package.xml
  turtlebot3_teleop/setup.py
Labels: bug

#1094 Bump 2.2.9
  .github/workflows/ros-ci.yml
  README.md
  turtlebot3/CHANGELOG.rst
  turtlebot3/CMakeLists.txt
  turtlebot3/package.xml
  turtlebot3_bringup/CHANGELOG.rst
  turtlebot3_bringup/package.xml
  turtlebot3_cartographer/CHANGELOG.rst
  turtlebot3_cartographer/package.xml
  turtlebot3_description/CHANGELOG.rst
  turtlebot3_description/package.xml
  turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf
  turtlebot3_example/CHANGELOG.rst
  turtlebot3_example/package.xml
  turtlebot3_example/setup.py
  turtlebot3_navigation2/CHANGELOG.rst
  turtlebot3_navigation2/package.xml
  turtlebot3_node/CHANGELOG.rst
  turtlebot3_node/package.xml
  turtlebot3_teleop/CHANGELOG.rst
  turtlebot3_teleop/package.xml
  turtlebot3_teleop/setup.py
Labels: bump

#1093 Bump 2.2.9
  .github/workflows/ros-ci.yml
  README.md
  turtlebot3/CHANGELOG.rst
  turtlebot3/CMakeLists.txt
  turtlebot3/package.xml
  turtlebot3_bringup/CHANGELOG.rst
  turtlebot3_bringup/package.xml
  turtlebot3_cartographer/CHANGELOG.rst
  turtlebot3_cartographer/package.xml
  turtlebot3_description/CHANGELOG.rst
  turtlebot3_description/package.xml
  turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf
  turtlebot3_example/CHANGELOG.rst
  turtlebot3_example/package.xml
  turtlebot3_example/setup.py
  turtlebot3_navigation2/CHANGELOG.rst
  turtlebot3_navigation2/package.xml
  turtlebot3_node/CHANGELOG.rst
  turtlebot3_node/package.xml
  turtlebot3_teleop/CHANGELOG.rst
  turtlebot3_teleop/package.xml
  turtlebot3_teleop/setup.py
Labels: bump
